---
output: word_document
params:
  report.data: 
  table: [some object]
---
 
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
 
library(kableExtra)
library(knitr)
library(tidyverse)
library(lubridate)
library(here)
 
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
 
```
 
```{r loaddata}
 
#Import CSV file, using filepath from params object created in shiny app
df <- read_csv(params$report.data)

```
 
```{r formatdf}
 
df <- df %>%
  
  # First, we'll make put a copy of the NCT number in a new field called Results_URL. This will be used later to construct links to the study results, where they exist. All other transformations appear in the order they will appear in the final Word doc.
  
  mutate(Results_URL = `NCT Number`) %>%
  
# R Markdown creates links in the format: [Text you read](link URL)
  
# To create our titles with links: 
  # Add brackets to the start and end of the existing URLs,
  # Add square brackets to the titles
  # Merge the two columns with unite.
# We're also adding the text that says "Title" with the opening square bracket. 
# Asterisks are markdown format to make text bold.
  
  mutate(`Study URL` = str_replace(`Study URL`,  "^", "(")) %>%
  mutate(`Study URL`= str_replace(`Study URL`, "$", ")")) %>%
  mutate(`Study Title` = str_replace(`Study Title`, "^", "**Title:** [")) %>%
  mutate(`Study Title` = str_replace(`Study Title`, "$", "]")) %>%
  unite(`Study Title`, `Study Title`, `Study URL`, sep = "", na.rm=TRUE) %>%
 
# Add heading to NCT numbers
  
  mutate(`NCT Number` = str_replace(`NCT Number`, "^", "**Study number:** ")) %>%
 
# Create "Alternative names or numbers:" line
  # Replace the pipe symbol that separates IDs with a semi-colon. The leading back-slashes are necessary to specify we want to replace the symbol rather than every gap between characters. 
  # Merge 'Other IDs' with Acronyms, separated by a semi-colon and ignoring any NA values.
  # Add line title.
  
  mutate(`Other IDs` = str_replace_all(`Other IDs`, "\\|", "; ")) %>%
  unite(`Other IDs`, `Other IDs`, Acronym, sep = "; ", na.rm=TRUE) %>%
  mutate(`Other IDs` = str_replace(`Other IDs`, "^", "**Alternative names or numbers:** ")) %>%
 
# change status to Title case from ALL CAPS, also puts a gap between word phase and the phase number  
# Add title to phases and replace any pipe separators with a slash
 
  mutate(Phases = str_to_title(Phases, locale = "en")) %>%
  mutate(Phases = str_replace_all(Phases, "(?<=[a-z])(?=\\d)", " ")) %>%
  mutate(Phases = str_replace_all(Phases, "\\|", "/")) %>%
  mutate(Phases = ifelse(is.na(Phases) | Phases == "", "not applicable", Phases)) %>% 
  mutate(Phases = str_replace(Phases, "^", "**Phase:** ")) %>%
 
# Add new, blank columns for 'methods or purpose' and 'population' fields
 
  mutate(MoP = "**Methods or purpose:** *(if not clear from title)*") %>%
  mutate(Population = "**Population:** ") %>%
  
# Add title to enrollment field  
  
  mutate(Enrollment = str_replace(Enrollment, "^", "**No. of patients:** ")) %>%
 
# Replace pipes that separate outcomes with bullet points & new lines in between. Next line adds title and bullet point for first idea.
 
  mutate(`Primary Outcome Measures` = str_replace_all(`Primary Outcome Measures`, "\\|", "\n\n •")) %>%
  mutate(`Primary Outcome Measures` = str_replace(`Primary Outcome Measures`, "^", "**Primary outcome(s):** \n\n •")) %>%
  
#change status to sentence case from capitals
#removes underscores and replace with a blank space 
  
  mutate(`Study Status` = str_to_sentence(`Study Status`, locale = "en")) %>% 
  mutate(`Study Status` = str_replace_all(`Study Status`, "\\_", " ")) %>%
  mutate(Status = str_replace(`Study Status`, "^", "**Status:** ")) %>%
  

  mutate(`Start Date` = str_replace_na(`Start Date`, "Not stated")) %>%
  mutate(`Start Date` = str_replace(`Start Date`, "^", "**Start date:** ")) %>%
  
  mutate(`Primary Completion Date` = str_replace_na(`Primary Completion Date`, "Not stated")) %>%
  mutate(`Primary Completion Date` = str_replace(`Primary Completion Date`, "^", "**Primary completion date:** ")) %>%
 
  mutate(`Completion Date` = str_replace_na(`Completion Date`, "Not stated")) %>%
  mutate(`Completion Date` = str_replace(`Completion Date`, "^", "**Study completion date:** ")) %>%

#In the Results_URL column, if results aren't available, paste in text
  mutate(Results_URL = case_when(`Study Results` == "NO" ~ paste("**Results**: not available at  clinicaltrials.gov"), TRUE ~ Results_URL))  %>%
 
#In the Results URL column, if results are available, add an 'available' hyperlink (square brackets). Add the beginning of the URL and merge with the NCT number (Results_URL = NCT number as per line 35)   
  mutate(Results_URL= case_when(`Study Results` == "YES" ~ paste("**Results**: [Available](https://clinicaltrials.gov/ct2/show/results/", Results_URL, ")", sep = ""), TRUE ~ Results_URL))  %>%
  
#create a blank column, so entries are separated by a line in Word 
mutate(blank = "\\")  

 
df <- select(df, `Study Title`, `NCT Number`, `Other IDs`, Phases, MoP, Population, Enrollment, `Primary Outcome Measures`, Status, `Start Date`, `Primary Completion Date`, `Completion Date`, Results_URL, blank) 
 
 
kable(df[1:14], col.names = NULL) 
```