---
output: word_document
params:
  report.data: 
  table: [some object]
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
library(lubridate)
library(here)

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

# Import CSV file
df <- read_csv(params$report.data)

df <- df %>%
  mutate(Results_URL = `NCT Number`) %>%
  mutate(`Study URL` = str_replace(`Study URL`, "^", "(")) %>%
  mutate(`Study URL` = str_replace(`Study URL`, "$", ")")) %>%
  mutate(`Study Title` = str_replace(`Study Title`, "^", "**Title:** [")) %>%
  mutate(`Study Title` = str_replace(`Study Title`, "$", "]")) %>%
  unite(`Study Title`, `Study Title`, `Study URL`, sep = "", na.rm = TRUE) %>%
  mutate(`NCT Number` = str_replace(`NCT Number`, "^", "**Study number:** ")) %>%
  mutate(`Other IDs` = str_replace_all(`Other IDs`, "\\|", "; ")) %>%
  unite(`Other IDs`, `Other IDs`, Acronym, sep = "; ", na.rm = TRUE) %>%
  mutate(`Other IDs` = str_replace(`Other IDs`, "^", "**Alternative names or numbers:** ")) %>%
  mutate(Phases = str_to_title(Phases)) %>%
  mutate(Phases = str_replace_all(Phases, "(?<=[a-z])(?=\\d)", " ")) %>%
  mutate(Phases = str_replace_all(Phases, "\\|", "/")) %>%
  mutate(Phases = ifelse(is.na(Phases) | Phases == "", "not applicable", Phases)) %>%
  mutate(Phases = str_replace(Phases, "^", "**Phase:** ")) %>%
  mutate(MoP = "**Methods or purpose:** *(if not clear from title)*") %>%
  mutate(Population = "**Population:** ") %>%
  mutate(Enrollment = str_replace(Enrollment, "^", "**No. of patients:** ")) %>%
  mutate(`Primary Outcome Measures` = str_replace_all(`Primary Outcome Measures`, "\\|", "\n\n •")) %>%
  mutate(`Primary Outcome Measures` = str_replace(`Primary Outcome Measures`, "^", "**Primary outcome(s):** \n\n •")) %>%
  mutate(`Study Status` = str_to_sentence(`Study Status`)) %>%
  mutate(`Study Status` = str_replace_all(`Study Status`, "\\_", " ")) %>%
  mutate(Status = str_replace(`Study Status`, "^", "**Status:** ")) %>%
  mutate(`Start Date` = str_replace_na(`Start Date`, "Not stated")) %>%
  mutate(`Start Date` = str_replace(`Start Date`, "^", "**Start date:** ")) %>%
  mutate(`Primary Completion Date` = str_replace_na(`Primary Completion Date`, "Not stated")) %>%
  mutate(`Primary Completion Date` = str_replace(`Primary Completion Date`, "^", "**Primary completion date:** ")) %>%
  mutate(`Completion Date` = str_replace_na(`Completion Date`, "Not stated")) %>%
  mutate(`Completion Date` = str_replace(`Completion Date`, "^", "**Study completion date:** ")) %>%
  mutate(Results_URL = case_when(
    `Study Results` == "NO" ~ "**Results**: not available at clinicaltrials.gov",
    `Study Results` == "YES" ~ paste("**Results**: [Available](https://clinicaltrials.gov/ct2/show/results/", Results_URL, ")", sep = ""),
    TRUE ~ Results_URL
  )) %>%
  mutate(blank = "\\")

# Collapse all fields into one column with line breaks
df$output <- apply(select(df, `Study Title`, `NCT Number`, `Other IDs`, Phases, MoP, Population,
                          Enrollment, `Primary Outcome Measures`, Status, `Start Date`, 
                          `Primary Completion Date`, `Completion Date`, Results_URL, blank), 
                   1, function(x) paste(x, collapse = "\n\n"))

# Display a one-column table
kable(data.frame(output = df$output), col.names = NULL, escape = FALSE)

---