---
output: word_document
params:
  report.data: NA
  table: [some object]
---
 
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
 
library(kableExtra)
library(knitr)
library(tidyverse)
library(lubridate)

 
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
 
```
 
```{r loaddata}
 
#Import CSV file, using filepath from params object created in shiny app
df <- read_csv(params$report.data)
 
```
 
```{r formatdf}

# previous issues with this script have arisen from...

# R assuming that columns are the wrong data type on import
# ISRCTN changing their column headings
# ISRCTN reusing or reordering column headings

# Worth checking all these if troubleshooting in future.  

df <- df 
colnames <- (make.unique(names(df)))
 
#create link in the ISRCTN column 
#add heading to the Title column and merge ISRCTN and title columns

df <- df %>%

  mutate(URL = ISRCTN) %>%
  mutate(URL = str_replace(URL,"^", "https://www.isrctn.com/")) %>%
  mutate(URL = str_replace(URL, "^", "("))%>%
  mutate(URL = str_replace(URL, "$", ")"))%>%
  mutate(Title = str_replace(Title, "^", "**Title:** [")) %>%
  mutate(Title = str_replace(Title, "$", "]")) %>%
  unite(Title, Title, URL, sep = "", na.rm=TRUE, remove = FALSE) %>%
 
# Study number line created from ISRCTN column 
 
  mutate(ISRCTN = str_replace(ISRCTN, "^", "**Study number:** ")) %>%
 
# Convert columns with trial registry identifiers in into character columns (only strictly necessary if all entries are blank), then replace 'Nil known' and blank entries with NA. 
# We'll combine the EudraCT/CTIS number; IRAS number and clinicaltrials.gov number columns (not often filled in) to form a single column containing all these identifiers. 

  mutate(`EudraCT/CTIS number`= as.character(`EudraCT/CTIS number`)) %>%
  mutate(`ClinicalTrials.gov number`= as.character(`ClinicalTrials.gov number`)) %>%
  
  mutate(`EudraCT/CTIS number`= na_if(`EudraCT/CTIS number`, "Nil known"))  %>%
  mutate(`ClinicalTrials.gov number`= na_if(`ClinicalTrials.gov number`, "Nil known")) %>%
 
  mutate(`EudraCT/CTIS number`= na_if(`EudraCT/CTIS number`,"Nil Known"))  %>%
  mutate(`ClinicalTrials.gov number`= na_if(`ClinicalTrials.gov number`, "Nil Known")) %>% 
  
  mutate(`EudraCT/CTIS number`= na_if(`EudraCT/CTIS number`,"N/A"))  %>%
  mutate(`ClinicalTrials.gov number`= na_if(`ClinicalTrials.gov number`, "N/A")) %>%
  
  mutate(`EudraCT/CTIS number`= na_if(`EudraCT/CTIS number`,"Nil known."))  %>%
  mutate(`ClinicalTrials.gov number`= na_if(`ClinicalTrials.gov number`, "Nil known.")) %>%  
  
  mutate(`EudraCT/CTIS number`= na_if(`EudraCT/CTIS number`,""))  %>%
  mutate(`ClinicalTrials.gov number`= na_if(`ClinicalTrials.gov number`, "")) %>%
    
  unite(`EudraCT/CTIS number`, `EudraCT/CTIS number`, `IRAS number`,`ClinicalTrials.gov number` , sep = "; ", na.rm=TRUE) %>%
  mutate(`EudraCT/CTIS number` = case_when(`EudraCT/CTIS number`== "" ~ "Not stated",
TRUE ~ `EudraCT/CTIS number`))  %>%
  mutate(`EudraCT/CTIS number` = str_replace(`EudraCT/CTIS number`, "^", "**Alternative names or numbers:** ")) %>%
  
# Add title to existing phase column, remove entries that say Not Applicable, remove NAs
 
  mutate(Phase = str_replace_all(Phase, "Not Applicable", "Not stated")) %>%
  mutate(Phase = str_replace_na(Phase, "Not stated")) %>%
  mutate(Phase = str_replace(Phase, "^", "**Phase:** ")) %>%
 
# Add new, blank columns for 'methods or purpose' field
 
  mutate(MoP = "**Methods or purpose:** *(if not clear from title)*") %>%
  
# Population from Age group column. Merge with Sex column.
# When trial recruits both male and female, it shows as 'both' - we may need to add something extra here  
  
  mutate(`Age group` = str_replace(`Age group`, "^", "**Population:** ")) %>%
  unite(`Age group`, `Age group`, Sex , sep = "; ", na.rm=TRUE) %>%
  mutate(`Age group` = str_replace(`Age group` , "Both" , "Male and Female")) %>%
 
 
# Number of patients from Target number of participants column 
 
  mutate(`Target number of participants` = str_replace(`Target number of participants`, "^", "**Participants:** ")) %>%
       
# Add new, blank column for 'Primary outcomes' field
 
  mutate(Primary_outcomes = "**Primary outcomes:**") %>%
 
# Status from Overall study status column. 
 
  mutate(`Overall study status` = str_replace(`Overall study status`, "^", "**Status:** ")) %>%
 
# Start date from Date of first enrolment column
# Change date format to month & year. Note that if you're viewing the input file in Excel it may reformat dates to DDMMYYYY whereas in the original CSV they're YYYYMMDD. 
 
  mutate(`Date of first enrolment`= format(ymd(`Date of first enrolment`),"%B %Y")) %>%
  mutate(`Date of first enrolment` = str_replace(`Date of first enrolment`, "^", "**Start date:** ")) %>%  
 
# Create primary completion date column - info not available in ISRCTN but this keeps the report format consistent with other registries.  
  
  mutate(`Primary completion date` = "**Primary completion date:** Not stated" ) %>%  
 
# Study completion date from Completion date column. 
# Change date format to month & year
  
  mutate(`Completion date`= format(ymd(`Completion date`),"%B %Y")) %>%
  mutate(`Completion date` = str_replace(`Completion date`, "^", "**Study completion date:** ")) %>%
  
 
# Create a new column from Basic results column. There's actually two columns with that name so we have to specify it by index number. Meghna points out there's a function to make names unique in the first instance: (make.unique(names(df))) after importing the CSV
#when column has results, add link to ISRCTN record 
#when column has no results, add text to say 'results not available from ISRCTN' 
 
  mutate(`Results available` = 
         case_when(is.na(`Basic results...8`) != TRUE ~ paste("**Results**: [Available at ISRCTN]", URL, sep = ""),
                  (is.na(`Basic results...8`) == TRUE ~ "**Results**: not available at ISRCTN"))) %>%
 
#create a blank column to add a space between entries in Word doc 
  mutate(blank = "\\")  

df<-select(df,Title,ISRCTN,`EudraCT/CTIS number`,Phase,MoP,`Age group`,`Target number of participants`,Primary_outcomes, `Overall study status`, `Date of first enrolment`,`Primary completion date`,`Completion date`,`Results available`, blank)
 
kable(df[1:14], col.names = NULL) 


```